### ISSUE TITLE
Microsoft Defender Smartscreen 风险提示

### ISSUE THREAD

**Issue by lizhongyue248** [mashirot/gugu-aod#1]
![image](https://github.com/mashirot/gugu-aod/assets/29678316/f59fa670-95d3-426f-83a1-bfe1e8ecd23a)

是不是调用了某些系统 API 或者第三方库造成这个问题的呀？

**Comment by ShiinaKin** [comment]
可能是签名问题吧，我不太懂加壳/签名这块，直接package的，你不放心的话可以自己编译

**Comment by lizhongyue248** [comment]
感觉不是，如果是签名这块应该弹出的是 Windows 的 uac，不应该是这个

**Comment by ShiinaKin** [comment]
你的问题是什么呢，这个就是没有微软授信的签名证书导致的，你要运行可以右键exe，解除锁定，或者该界面-更多信息-仍要运行，不放心可以自己看源码，编译
